apiVersion: v1
description: A Helm chart for Tekton Pipelines
name: tekton-pipeline
version: 0.44.3
appVersion: 0.44.3
icon: https://avatars2.githubusercontent.com/u/47602533
home: https://github.com/equinor/tekton-helm-chart